%YAML 1.1
# -*- coding: UTF-8, tab-width: 2 -*-
---

name: 'Install ghciu'
description: 'Install ghciu'

inputs:

  nodejs_version:
    description: 'Which node.js to install. Major version only, as a number, 0 = skip.'
    required: false
    default: 20

  npm_version:
    description: 'Whether to install a specific npm version.'
    required: false
    default: 0


runs:
  using: 'composite'
  steps:

    - name: "Install Node.js v${{ inputs.nodejs_version }}"
      uses: actions/setup-node@v4
      if: "${{ inputs.nodejs_version > 0 }}"
      with:
        node-version: "${{ inputs.nodejs_version }}.x"

    - name: "Install npm v${{ inputs.npm_version }}"
      shell: bash
      if: "${{ inputs.npm_version > 0 }}"
      run: npm install --global npm@"${{ inputs.npm_version }}"

    - name: 'Install CI utils'
      shell: bash
      run: >
        sudo mv --verbose --no-target-directory --
        "${GITHUB_ACTION_PATH%/*/*}" "$DEST"
        && sudo -E "$DEST"/install_globally.sh
      env:
        DEST: /usr/lib/ghciu














...
