%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#   with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 2 -*-
---

on:
  push:
    branches:
      - '*'

jobs:
  job_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Install CI utils'
        run: >
          sudo -E sh -c 'R=mk-pmb/github-ci-util-2405-pmb; B=master
          ; mkdir -p /ghciu && cd /ghciu && wget -q --
          "https://github.com/$R/archive/refs/heads/$B.tar.gz"
          && tar --strip-components=1 -xvzf "$B.tar.gz"
          && ./install_globally.sh'

      - run: ghciu vdo date -R
      - run: ghciu vdo megafail || true



...
