%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#   with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 2 -*-
---

name: '☂ CI tests'

on:
  push:
    branches:
      - '*'

env:
  GHCIU_STEPSUMM_RELEASE_TAG: 'rolling/auto-ci-release'
  # ^-- When set, the install action generates a release badge link.


jobs:
  job_ci:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # required for publishing a release.

    steps:
      - uses: actions/checkout@v4

      ########################################################################
      # Branch selection in the "uses" task
      #=======================================================================
      # The part after `@` specifies the branch to use.
      # I need `experimental` here in order to conveniently test that branch.
      # However, in all other repos you should probably use "v1" instead:
      # - uses: mk-pmb/github-ci-util-2405-pmb/act/install@v1
      - uses: mk-pmb/github-ci-util-2405-pmb/act/install@experimental

      - run: ghciu vdo date -R
      - run: ghciu vdo megafail || true

      - name: 'Add debug files to auto-release'
        if: always()
        run: >
          mkdir --parents -- tmp.release &&
          zip -qr9 tmp.release/debug_node_modules.zip --
          node_modules/
          package.json
          package-lock.json

      - name: 'Publish auto-release'
        if: always()
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: True
          artifactErrorsFailBuild: True
          artifacts: 'tmp.release/*'
          body: ''
          makeLatest: False
          prerelease: True
          removeArtifacts: True # Remove old files from release.
          commit: '${{ github.sha }}'
          tag: '${{ env.GHCIU_STEPSUMM_RELEASE_TAG }}'


  wipe_old_workflows:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:

      # Branch selection in the "uses" task: see above
      - uses: mk-pmb/github-ci-util-2405-pmb/act/purge-old-workflow-runs@experimental
        with:
          api_token: '${{ github.token }}'
          older_than: '2 minutes ago'



...
