%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#   with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 2 -*-
---

on:
  push:
    branches:
      - '*'

jobs:
  job_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      ########################################################################
      # Branch selection in the "uses" task
      #=======================================================================
      # The part after `@` specifies the branch to use.
      # I need `experimental` here in order to conveniently test that branch.
      # However, in all other repos you should probably use "v1" instead:
      # - uses: mk-pmb/github-ci-util-2405-pmb/act/install@v1
      - uses: mk-pmb/github-ci-util-2405-pmb/act/install@experimental

      - run: ghciu vdo date -R
      - run: ghciu vdo megafail || true



...
